{% set version = "3.0.0" %}
{% set hash_type = "sha256" %}
{% set hash_val = "2ec9ca7d31db492a1c5a024a51bd497be3b15b7229232365a55b2765dd5eef68" %}

package:
  name: pescador
  version: {{ version }}

source:
  fn: pescador-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pescador/pescador-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=48

  run:
    - python >=3.7
    - pyzmq >=18.0
    - numpy >=1.9
    - decorator >=4.0
    - msgpack-python >=1.0

test:
  # Python imports
  imports:
    - pescador

about:
  home: http://github.com/pescadores/pescador
  license: ISC
  summary: 'Multiplex generators for incremental learning'
  license_family: OTHER

extra:
  recipe-maintainers:
    - bmcfee
