{% set version = "2.0.0rc0" %}
{% set hash_type = "sha256" %}
{% set hash_val = "da03558e199a99dd434da21fb39d1826f228647d59f5aa516962139fa86c291c" %}

package:
  name: pescador
  version: {{ version }}

source:
  fn: pescador-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pescador/pescador-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - joblib >=0.9
    - six >=1.8
    - pyzmq >=15.0
    - numpy >=1.9
    - decorator >=4.0

test:
  # Python imports
  imports:
    - pescador

about:
  home: http://github.com/pescadores/pescador
  license: ISC
  summary: 'Multiplex generators for incremental learning'
  license_family: OTHER

extra:
  recipe-maintainers:
    - bmcfee
