{% set version = "2.0.0" %}
{% set hash_type = "sha256" %}
{% set hash_val = "a2daa674256ee09e222aa86ed4991706c122ad6f7b05119916848626a69ffc04" %}

package:
  name: pescador
  version: {{ version }}

source:
  fn: pescador-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pescador/pescador-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - joblib >=0.9
    - six >=1.8
    - pyzmq >=15.0
    - numpy >=1.9
    - decorator >=4.0

test:
  # Python imports
  imports:
    - pescador

about:
  home: http://github.com/pescadores/pescador
  license: ISC
  summary: 'Multiplex generators for incremental learning'
  license_family: OTHER

extra:
  recipe-maintainers:
    - bmcfee
