# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Kdn/3bNiYCf4nh7Cg8o/4B9Ciu2OlhkY/u9n/BPARxQUEyZV/VgOi++28ZrrwPvNx++6rQye7EQs5DBsNV5cMwrw29iJyx2xKIGhgZmKSEXE0vpoP8BHugWvpdVXVsniy/ATNk0IGmAfTV6p1dktyPlh9L/86SMiaPTqTQg5C1yt38GP36/BWlyPWRILh9gVPmjPyGLpsBx+7te6dKdMoArw0lH/K8bFOetOKnm2QM81pibC9s9uCspAGZiGr242aH1B2KYhjYi+JqGndgvDvQZtxvKn7A/HEJ+/hiXJs2i0xVWXE0FDewL5ADBM8VUpBu68hBzVHQvEIxtxrlWzm00jAp+fS4p4OWga7f8Fo7LkAgZIHKH3a3GbPEmyN9WJnxbDTbr1NsWRJKnVjlYrhMobZT1kjqlKlaD/gkI8PsS4WaRcIcCtouMJIU9lYdedgzJAS88/SxEH2zOR5ViE8OixbxWUrxKBTwGHmRMjjC4QwLblmIl09dJkImXAjx9ttRW+C3w3wnvAQt98EhOnVL/d1syDq7aVXXpW0JcaM/y0eI4nQ8C5ebSVu3t4LgY9bDV6GJ0lI2JLd1O/cS3FFwZqHPUxigRayjXhPZQNC6/78lOYvs02rqvZVpbeP/8oBSVm6aZq48NotYx6fKx/MUOENRgb3mheXkK5Yle6/J8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
