travis:
  secure:
    BINSTAR_TOKEN: iHapdhkxtv/qZbgmRNCoiYSMlZa3FkwR2rZnNbN0q4qlR2po++PviCYDlFrwRF3ZLAeYfbWOxBWSlilJ1ymU0IJoR3NyizlMZKMr5gfDgAO05MV52Al96JYPXEEG7rttX5p6yO3v4NPZ+rzKFFWI4iu3KnZxLqdI95nQZueRKeJ5LNdzPQeCiOqPwlvRWwgg/l7P8zcdwiu9hJFBPj4f2rbZiOBwy9UZQH6sGNidI39HBLcf3I5n/83HJ0MJFKU32ixBDcM9QlzJfoH3/4KWp1jUaXnYRrvvFmCkVe2k8r27VfRW+/bYql+hh5H0RxpISkuRKwKzTZo0o8AOu2ztlEQ+pr8yQMbvSKvsapZ5HN2baDRDLw7NG+TBgU2K2ztU4FpLUXz72Ll/hvM1nYlX69WgJMnTZyZdGTOYOyOppycB2oaSSgJxQcC0kgn6GUIP0cDsbbDeL+siqqfvKRTlQoTGAxiQUgj5k4vR7JoXlgBiETLE/3TBpSbFDJBv7LwDH7zYiZRuMaDIkzeDmmCgyMPt2+wPDk1VhQ/BgcqJS68zgtbnJtY2bwVXc11XfTfHkF51SVQsjqKXDls8uqqraFN+D4Bav296ppUXWaiC59Zk+2PV2Zr3BPx2tFOh1KyGZWJ+B0f+24mzvSmpuLvWwQzQUNtsdhNYq42P6p1udKE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
