travis:
  secure:
    BINSTAR_TOKEN: Kdn/3bNiYCf4nh7Cg8o/4B9Ciu2OlhkY/u9n/BPARxQUEyZV/VgOi++28ZrrwPvNx++6rQye7EQs5DBsNV5cMwrw29iJyx2xKIGhgZmKSEXE0vpoP8BHugWvpdVXVsniy/ATNk0IGmAfTV6p1dktyPlh9L/86SMiaPTqTQg5C1yt38GP36/BWlyPWRILh9gVPmjPyGLpsBx+7te6dKdMoArw0lH/K8bFOetOKnm2QM81pibC9s9uCspAGZiGr242aH1B2KYhjYi+JqGndgvDvQZtxvKn7A/HEJ+/hiXJs2i0xVWXE0FDewL5ADBM8VUpBu68hBzVHQvEIxtxrlWzm00jAp+fS4p4OWga7f8Fo7LkAgZIHKH3a3GbPEmyN9WJnxbDTbr1NsWRJKnVjlYrhMobZT1kjqlKlaD/gkI8PsS4WaRcIcCtouMJIU9lYdedgzJAS88/SxEH2zOR5ViE8OixbxWUrxKBTwGHmRMjjC4QwLblmIl09dJkImXAjx9ttRW+C3w3wnvAQt98EhOnVL/d1syDq7aVXXpW0JcaM/y0eI4nQ8C5ebSVu3t4LgY9bDV6GJ0lI2JLd1O/cS3FFwZqHPUxigRayjXhPZQNC6/78lOYvs02rqvZVpbeP/8oBSVm6aZq48NotYx6fKx/MUOENRgb3mheXkK5Yle6/J8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
